version: '2'

services:

  plex:
    container_name: plex
    image: plexinc/pms-docker
    restart: always
    ports:
      - 32400:32400/tcp 
      - 3005:3005/tcp 
      - 8324:8324/tcp 
      - 32469:32469/tcp 
      - 1900:1900/udp 
      - 32410:32410/udp 
      - 32412:32412/udp 
      - 32413:32413/udp 
      - 32414:32414/udp 
    environment:
      - TZ="Europe/Athens" # Change it with yours
      - PLEX_CLAIM="<CLAIM CODE>" # get it from https://www.plex.tv/claim/
      - ADVERTISE_IP="http://your_ip:32400/" # Your IP
    hostname: PlexServer
    volumes: 
      - ./database:/config 
      - ./transcode/temp:/transcode 
      - /myPath/Movies:/data/Movies # Change it with your movies path
      - /myPath/TV:/data/TV # Change it with your tv shows path
    network_mode: "host"